### ISSUE TITLE
complex skeleton / INSTALL.md inconsistency

### ISSUE THREAD

**Issue by elazar** [whatthejeff/breeze#8]
The BINARIES section of `INSTALL.md` includes `myapp/helpers` and `myapp/models` in the output for creating a new project with a complex project structure, but `skeleton/complex` doesn't actually include those directories. Either `INSTALL.md` should be updated to have mention of those directories removed or `skeleton/complex` should be updated so its structure includes those directories.

**Comment by whatthejeff** [comment]
I think I will update `INSTALL.md` for now.

**Comment by whatthejeff** [comment]
Actually, I think I just forgot to drop `.gitignore` files in the empty directories.  I will update the `skeleton` directory instead.
